# Generated by Django 2.2.10 on 2020-07-29 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200729_0541'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('question', 'vote')},
        ),
    ]
