# Generated by Django 2.2.10 on 2020-07-29 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200729_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='voted_by',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
