# Generated by Django 2.2.10 on 2020-07-29 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20200729_0707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='choice',
        ),
        migrations.AddField(
            model_name='answer',
            name='choice',
            field=models.ManyToManyField(blank=True, related_name='answers', to='polls.Choice'),
        ),
    ]
