# Generated by Django 2.2.10 on 2020-07-29 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20200729_0739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='choice',
            new_name='choices',
        ),
    ]
